# Generated by Django 5.0.4 on 2024-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_receiver_alter_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
