# Generated by Django 5.0.4 on 2024-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Node', 'Node.js'), ('Angular', 'Angular'), ('Vue', 'Vue.js'), ('Bootstrap', 'Bootstrap'), ('jQuery', 'jQuery'), ('Django', 'Django'), ('Flask', 'Flask'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('SQL', 'SQL'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Git', 'Git'), ('AWS', 'Amazon Web Services (AWS)'), ('Azure', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform (GCP)'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Scikit-learn', 'Scikit-learn'), ('Pandas', 'Pandas'), ('NumPy', 'NumPy'), ('Matplotlib', 'Matplotlib')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('intern', 'Intern'), ('other', 'Other'), ('django_developer', 'Django Developer'), ('fullstack_developer', 'Fullstack Developer'), ('mern_stack_developer', 'MERN Stack Developer'), ('front_end_developer', 'Front-End Developer'), ('back_end_developer', 'Back-End Developer'), ('software_engineer', 'Software Engineer'), ('data_scientist', 'Data Scientist'), ('machine_learning_engineer', 'Machine Learning Engineer')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='accounts.skill'),
        ),
    ]
