# Generated by Django 5.0.4 on 2024-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skill_remove_profile_status_profile_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Node', 'Node.js'), ('Angular', 'Angular'), ('Vue', 'Vue.js'), ('Bootstrap', 'Bootstrap'), ('jQuery', 'jQuery'), ('Django', 'Django'), ('Flask', 'Flask'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('SQL', 'SQL'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Git', 'Git'), ('AWS', 'Amazon Web Services (AWS)'), ('Azure', 'Microsoft Azure'), ('GCP', 'Google Cloud Platform (GCP)'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Scikit-learn', 'Scikit-learn'), ('Pandas', 'Pandas'), ('NumPy', 'NumPy'), ('Matplotlib', 'Matplotlib')], related_name='profiles', to='accounts.skill'),
        ),
    ]
