# Generated by Django 5.0.4 on 2024-04-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='profiles', to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('react', 'React'), ('node', 'Node.js'), ('angular', 'Angular'), ('vue', 'Vue.js'), ('bootstrap', 'Bootstrap'), ('jquery', 'jQuery'), ('django', 'Django'), ('flask', 'Flask'), ('python', 'Python'), ('java', 'Java'), ('c_plus_plus', 'C++'), ('c_sharp', 'C#'), ('ruby', 'Ruby'), ('php', 'PHP'), ('sql', 'SQL'), ('mongodb', 'MongoDB'), ('postgresql', 'PostgreSQL'), ('git', 'Git'), ('aws', 'Amazon Web Services (AWS)'), ('azure', 'Microsoft Azure'), ('gcp', 'Google Cloud Platform (GCP)'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('scikit_learn', 'Scikit-learn'), ('pandas', 'Pandas'), ('numpy', 'NumPy'), ('matplotlib', 'Matplotlib')], max_length=100),
        ),
    ]
