# Generated by Django 5.0.4 on 2024-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_skills_alter_skill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Intern', 'Intern'), ('Other', 'Other'), ('Django Developer', 'Django Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('MERN Stack Developer', 'MERN Stack Developer'), ('Front-End Developer', 'Front-End Developer'), ('Back-End Developer', 'Back-End Developer'), ('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Machine Learning Engineer', 'Machine Learning Engineer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('Node.js', 'Node.js'), ('Angular', 'Angular'), ('Vue.js', 'Vue.js'), ('Bootstrap', 'Bootstrap'), ('jQuery', 'jQuery'), ('Django', 'Django'), ('Flask', 'Flask'), ('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('Ruby', 'Ruby'), ('PHP', 'PHP'), ('SQL', 'SQL'), ('MongoDB', 'MongoDB'), ('PostgreSQL', 'PostgreSQL'), ('Git', 'Git'), ('Amazon Web Services (AWS)', 'Amazon Web Services (AWS)'), ('Microsoft Azure', 'Microsoft Azure'), ('Google Cloud Platform (GCP)', 'Google Cloud Platform (GCP)'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('Scikit-learn', 'Scikit-learn'), ('Pandas', 'Pandas'), ('NumPy', 'NumPy'), ('Matplotlib', 'Matplotlib')], max_length=100),
        ),
    ]
