# Generated by Django 5.0.4 on 2024-05-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_experience_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Intern', 'Intern'), ('Other', 'Other'), ('Django Developer', 'Django Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('MERN Stack Developer', 'MERN Stack Developer'), ('Front-End Developer', 'Front-End Developer'), ('Back-End Developer', 'Back-End Developer'), ('Software Engineer', 'Software Engineer'), ('Data Scientist', 'Data Scientist'), ('Machine Learning Engineer', 'Machine Learning Engineer')], default='', max_length=100),
        ),
    ]
